### ISSUE TITLE
.deb installation fails on Debian 8

### ISSUE THREAD

**Issue by klausi** [kegato/letsencrypt-inwx#1]
```
Preparing to unpack letsencrypt-inwx_1.0.0_amd64.deb ...
Unpacking letsencrypt-inwx (1.0.0) ...
dpkg: dependency problems prevent configuration of letsencrypt-inwx:
 letsencrypt-inwx depends on libgcc1 (>= 1:4.9.3); however:
  Version of libgcc1:amd64 on system is 1:4.9.2-10+deb8u1.

dpkg: error processing package letsencrypt-inwx (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 letsencrypt-inwx
```

I guess that cannot be fixed and I need to either upgrade to Debian 9 or build myself?

**Comment by ciphax** [comment]
The deb file from the release page was built by travis ci which uses Ubuntu 14.04 as build environment. I don't think there is another way than building yourself or upgrading your version of libgcc since your libgcc version is older than the libgcc version used by Ubuntu 14.04. You can find instructions for building in the [readme](https://github.com/kegato/letsencrypt-inwx#building).

**Comment by klausi** [comment]
Thanks, building manually now.
