### ISSUE TITLE
tool hangs on first run

### ISSUE THREAD

**Issue by wilhelmy** [kegato/letsencrypt-inwx#11]
```
root@letsencrypt ~# ps auxw
USER      PID  %CPU %MEM    VSZ   RSS TT  STAT STARTED    TIME COMMAND
certbot 28367 100.0  0.2  68684 30524 13  R+J  15:36   3:01.71 /srv/letsencrypt/.cargo/bin/letsencrypt-inwx create -c /srv/letsencrypt/.config/letsencrypt-inwx-cred -d _acme-challenge.topsecret -v omitted
```

FreeBSD 11.1, rust v1.26.2

**Comment by ciphax** [comment]
I did not test this crate on freebsd since I'm not using it. However it's hard to believe for me that this crate is causing the problem.
The only loop in this crate (apart from foreach loops)  looks like [this](https://github.com/kegato/letsencrypt-inwx/blob/master/src/main.rs#L113):
```rust
if !matches.is_present("nodnscheck") {
	println!("Waiting for the dns record to be publicly visible...");

	let start = Instant::now();
	let mut wait_secs = 5;

	loop {
		// timeout after 10 minutes
		if start.elapsed() > Duration::from_secs(60 * 10) {
			return Err("timeout!".to_owned());
		}

		if check_txt_record(domain, value) {
			break;
		}

		wait_secs *= 2;

		sleep(Duration::from_secs(wait_secs));
	}

	println!("=> done!");
}
```

So while it could loop for up to around 10 minutes it should not be possible for it to cause 100% cpu usage since it uses `sleep`.
Could you try to run `letsencrypt-inwx create` with the `--no-dns-check` flag to test if this is the problem?

**Comment by ciphax** [comment]
I hope you could solve your problem. If your problem still persists I can reopen this issue.
